'''
Entire problib setup pipeline
'''

# 1. IMPORTS

# 2. ENTITY DEFS

# 3. ENV SETUP

## (OPTIONAL) ENGINE SPEC
### GLOBAL PARAMETRIC STRUCTURE
### GLOBAL DEFAULT STRUCTURE
### LOCAL PARAMETRIC STRUCTURE
### LOCAL DEFAULT STRUCTURE

## ENGINE INITIALIZATION
### STATE SPACE
### ACTION SPACE
### ENTITY SPACE

### Fixed structure
### Entities and groups
### Indexes

# 4. GYM SETUP
